######################################
#          Fishkg 6.2 Config
#             Made by Efe
######################################
config: 62
#=======================#
#     Config Guide
#=======================#
#
# >>>>> Config 설정 가이드입니다. **실제 설정은 더 아래에 있습니다.**
#
#
#general:  <--- 기본 설정
#  autoStart: false   <--- 플러그인 로드시, 자동으로 대회가 시작될지 여부
#  usePermissions: true   <--- 펄미션 사용 여부 (false: OP 권한이 필요한 행위 외에 모든 것에 권한을 가짐)
#  debug: false   <--- 디버그
#  updateCheck: true   <--- 업데이트 체크 여부
#
#fish:  <--- 물고기 설정
#  enable: true   <--- 물고기 아이템에 DisplayName과 Lore 등 데이터 추가 여부
#  addGrade: true   <--- 물고기 아이템에 등급 추가 여부
#  trashPercent: 5   <--- 쓰레기가 나올 확률 (0: 나오지 않음)
#  forceTrashFish: false   <--- 쓰레기 아이콘을 물고기로 설정할지 여부
#  separateBiome: true   <--- 바이옴마다 다른 물고기가 뜰지 여부 (false: 바이옴에 상관없이 모든 물고기가 낚임)
#  titleMessage: false   <--- [1.8, TitleAPI 플러그인 필요]물고기 낚을 경우 타이틀 메세지 전송 여부  http://www.spigotmc.org/resources/titleapi.1325/
#  announceRange: 0   <--- 물고기 낚을 경우 반경 N 미터 이내의 플레이어에게 메세지 (0으로 하면 전체 알림)
#  announceRangeFirst: 0   <--- 새로운 1등이 탄생할 경우 반경 N 미터 이내의 플레이어에게 메세지 (0으로 하면 전체 알림)
#  announceRank: 3   <--- N등 이내의 플레이어를 순위에 표시 (3: 3등까지 표시)
#  prize:   <--- 새로운 1등이 나왔을때 설정
#    enable: false   <--- 기능 사용 여부
#    fireworks: true   <--- 랜덤 불꽃놀이 발사 여부
#    title: false   <--- [1.8, ProtocolLib 필요] 타이틀 메세지 전송 여부
#    console-commands:    <--- 서버 콘솔로 입력될 명령어 목록 (%player% = 플레이어 이름)
#    - give %player% Emerald 3   <--- 플레이어에게 에메랄드 3개를 줌
#    - effect %player% 8 20 1   <--- 점프 강화Ⅰ 1초
#  team:   <--- 팀전 설정
#    noTeamCanPlay: true   <--- 팀이 없어도 팀전 낚시대회에서 참여 가능 여부
#    showTeam: true   <--- 채팅 접두사로 팀이 보여질지 여부
#    randomJoin: false   <--- '/낚시대회 참가' 명령어로 레드와 블루 중 하나의 팀에 가입할지 여부 ('fish.join.bypass' 펄미션 소지시 '/낚시대회 참가 <팀>' 명령어 사용 가능)
#shop:   <--- 물고기 상점 설정 (Vault와 경제 플러그인 필요)
#  enable: true   <--- 물고기 상점 사용 여부
#  price: 1   <--- cm당 가격 (새우: 3~6cm, 범고래: 700~1000cm)
#  pricePoint: true   <--- 가격의 소숫점 반올림 여부
#  emerald: 0   <--- 이코노미 돈 대신 지불될 아이템의 코드 (0으로 할 경우 사용 안함)
#  grade:    <--- 물고기 등급에 따른 추가 가격 ('fish.addGrade'가 true여야함)
#    S: 0   <--- S급일때 추가 가격
#    A: 0   <--- A급일때 추가 가격
#    B: 0   <--- B급일때 추가 가격
#    C: 0   <--- C급일때 추가 가격
#    D: 0   <--- D급일때 추가 가격
#
#fishingRod:   <--- 낚싯대 설정
#  enable: false   <--- 기능성 낚싯대 사용 여부
#  craftable: false   <--- 기능성 낚싯대 조합 가능 여부 (조합법은 게시글 참조)
#  lure: false   <--- 미끼 시스템 기능 여부 ('/미끼' 명령어, true: 낚시할 경우 낚싯대의 '미끼' 인첸트가 삭제됨을 주의)
#  lureLv: 1   <--- 미끼 시스템 기능에서, 미끼 인첸트의 레벨 (1~8만 유효, 레벨×5초만큼 더 빨리 물고기가 잡힘)
#
#bucket:   <--- 물고기 양동이 설정
#  enable: false   <--- 물고기 양동이 사용 여부
#  row: 3   <--- 물고기 양동이 GUI에서 인벤토리의 줄 수 (3으로 설정할 경우 인벤토리 크기는 3줄×9칸＝27칸)
#
#
#
# >>>>> 아래부터 실제 Config 설정입니다.
#
#



general:
  autoStart: false
  usePermissions: true
  debug: false
  updateCheck: true
  
fish:
  enable: true
  addGrade: true
  trashPercent: 5
  forceTrashFish: false
  separateBiome: true
  titleMessage: false
  announceRange: 0
  announceRangeFirst: 0
  announceRank: 3
  prize:
    enable: false
    fireworks: true
    title: false
    console-commands: 
    - give %player% Emerald 3
    - effect %player% 8 20 1
  team:
    noTeamCanPlay: true
    showTeam: true
    randomJoin: false
  
shop:
  enable: false
  price: 1
  pricePoint: true
  emerald: 0
  grade: 
    S: 0
    A: 0
    B: 0
    C: 0
    D: 0

fishingRod:
  enable: false
  craftable: false
  lure: false
  lureLv: 3

bucket:
  enable: false
  row: 3

data-token:
  bucket: "§8FISHKG/§o양동이"

