#
#  TitleMaker v5.1 Config
#
#
config: 50

#
# * Config Guide *
#
# Config 가이드입니다.
# 자세한 설명은 배포 게시글 참조
#
#VVVVVVVVVVVVVVVV<
#
#update-check: true   <--- 플러그인 로드시 새로운 버전을 체크할지 여부 (true 권장)
#
#use:    <--- 기능 사용 ON/OFF
#  chat: true   <--- 채팅의 접두사로 칭호를 보일지 여부
#  hologram: false   <--- 닉네임 위에 홀로그램으로 칭호를 보일지 여부
#                         [** ProtocolLib 플러그인이 필요하며, 1.8 이상의 버전만 지원됩니다. **]
#                         http://dev.bukkit.org/bukkit-plugins/protocollib/
#  title-book: false   <--- 타이틀북 기능 사용 여부
#  title-tag: false   <--- 타이틀태그 기능 사용 여부
#  auto-main: false   <--- 대표 칭호가 없거나 초기화 되었을 경우 자동으로 첫 번째 칭호가 대표 칭호로 등록될지 여부
#
#newbie-title:    <--- 서버에 처음 접속한 플레이어에게 자동으로 칭호를 주는 기능
#  enable: false   <--- 기능 사용 여부
#  title: "&e[뉴비]"   <--- 지급될 칭호
#  auto-main: true   <--- 지급된 칭호가 자동으로 대표 칭호가 될지 여부
#
#title-info:    <--- UnlimitedRPG의 PlayerInfo 기능과 연동되어, 정보 창에 칭호 목록을 표시할지 여부
#                    [** UnlimitedRPG 플러그인이 필요하며, UnlimitedRPG v2.0 이상만 지원됩니다. **]
#                    http://blog.naver.com/cwjh1002/220078740064
#  enable: false   <--- 기능 사용 여부
#  slot: 16   <--- GUI에서의 슬롯 번호 (0~16)
#
#message:    <--- 메세지 설정, 설명 생략
#  receive: "%title%: 받은 칭호"
#  edit: "%number%: 칭호 번호, %old%: 바뀌기 전 칭호, %title%: 바뀐 후 칭호"
#  remove: "%number%: 칭호 번호, %title%: 삭제된 칭호"
#  book-name: ""
#  book-use: "%title%: 받은 칭호"
#  newbie: "%title%: 받은 칭호"
#
#AAAAAAAAAAAAAAAA<
#
# ▼▽ 아래에서 Config 내용을 수정해주세요 ▽▼
#

update-check: true

use: 
  chat: true
  hologram: false
  title-book: false
  title-tag: false
  auto-main: false

newbie-title: 
  enable: false
  title: "&e[뉴비]"
  auto-main: true

title-info: 
  enable: false
  slot: 16

message: 
  receive: "축하합니다! 당신은 %title% 칭호를 받았습니다!"
  edit: "당신의 %number%번째 칭호가 %old% 칭호에서 %title% 칭호로 바뀌었습니다."
  remove: "당신의 %number%번째 칭호인 %title% 칭호가 삭제되었습니다."
  book-name: "&e타이틀북"
  book-use: "타이틀북을 읽어 %title% 칭호를 받았습니다!"
  newbie: "서버에 처음 오셨군요! %title% 칭호를 받았습니다!"
