name: Fishkg-ExtraShop
version: 1.0
main: me.efe.fishkg.extrashop.FishkgExtraShop
author: Efe
softdepend: [EfeCore, Fishkg]
commands: 
  낚시상점:
    description: 낚시 상점 GUI를 엽니다.
permissions:
  fishkg.cmdshop:
    description: Can use cmd-shop.