package me.efe.efeauction;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import me.efe.efeitems.ItemStorage;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public enum AuctionMaterial {
	
	ACACIA_DOOR_ITEM(Material.ACACIA_DOOR_ITEM, AuctionLabel.BUILDING_SUPPLIES, "acacia door|아카시아 나무 문"),
	ACACIA_FENCE(Material.ACACIA_FENCE, AuctionLabel.BUILDING_SUPPLIES, "acacia fence|아카시아 나무 울타리"),
	ACACIA_FENCE_GATE(Material.ACACIA_FENCE_GATE, AuctionLabel.BUILDING_SUPPLIES, "acacia fence gate|아카시아 나무 울타리 문"),
	ACACIA_STAIRS(Material.ACACIA_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "acacia stairs|아카시아 나무 계단"),
	ACTIVATOR_RAIL(Material.ACTIVATOR_RAIL, AuctionLabel.BUILDING_SUPPLIES, "activator rail|활성화 레일"),
	APPLE(Material.APPLE, AuctionLabel.FARM_PRODUCE, "apple|사과"),
	ARMOR_STAND(Material.APPLE, AuctionLabel.FARM_PRODUCE, "armor stand|갑옷 거치대"),
	ARROW(Material.ARROW, AuctionLabel.TOOLS, "arrow|화살"),
	BAKED_POTATO(Material.BAKED_POTATO, AuctionLabel.FARM_PRODUCE, "baked potato|구운 감자"),
	BANNER(Material.BANNER, AuctionLabel.BUILDING_SUPPLIES, "banner|현수막"),
	BED(Material.BED, AuctionLabel.BUILDING_SUPPLIES, "bed|침대"),
	BIRCH_DOOR_ITEM(Material.BIRCH_DOOR_ITEM, AuctionLabel.BUILDING_SUPPLIES, "birch door|자작나무 문"),
	BIRCH_FENCE(Material.BIRCH_FENCE, AuctionLabel.BUILDING_SUPPLIES, "birch fence|자작나무 울타리"),
	BIRCH_FENCE_GATE(Material.BIRCH_FENCE_GATE, AuctionLabel.BUILDING_SUPPLIES, "birch fence gate|자작나무 울타리 문"),
	BIRCH_WOOD_STAIRS(Material.BIRCH_WOOD_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "birch stairs|자작나무 계단"),
	BLAZE_POWDER(Material.BLAZE_POWDER, AuctionLabel.POTIONS, "blaze powder|블레이즈 가루"),
	BLAZE_ROD(Material.BLAZE_ROD, AuctionLabel.POTIONS, "blaze rod|블레이즈 막대"),
	BONE(Material.BONE, AuctionLabel.MONSTER_DROPS, "bone|뼈다귀"),
	BOOK(Material.BOOK, AuctionLabel.OTHERS, "book|책"),
	BOOK_AND_QUILL(Material.BOOK_AND_QUILL, AuctionLabel.OTHERS, "book and quill|책"),
	BOOKSHELF(Material.BOOKSHELF, AuctionLabel.BUILDING_SUPPLIES, "bookshelf|책장"),
	BOW(Material.BOW, AuctionLabel.TOOLS, "bow|활"),
	BOWL(Material.BOWL, AuctionLabel.OTHERS, "bowl|그릇"),
	BREAD(Material.BREAD, AuctionLabel.FARM_PRODUCE, "bread|빵"),
	BRICK(Material.BRICK, AuctionLabel.BUILDING_SUPPLIES, "bricks|벽돌"),
	BRICK_STAIRS(Material.BRICK_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "bricks stairs|벽돌 계단"),
	BROWN_MUSHROOM(Material.BROWN_MUSHROOM, AuctionLabel.FARM_PRODUCE, "mushroom|버섯"),
	BUCKET(Material.BUCKET, AuctionLabel.TOOLS, "bucket|양동이"),
	CACTUS(Material.CACTUS, AuctionLabel.FARM_PRODUCE, "cactus|선인장"),
	CAKE(Material.CAKE, AuctionLabel.FARM_PRODUCE, "cake|케이크"),
	CARPET(Material.CARPET, AuctionLabel.BUILDING_SUPPLIES, "carpet|카펫"),
	CARROT_ITEM(Material.CARROT_ITEM, AuctionLabel.FARM_PRODUCE, "carrot|당근"),
	CARROT_STICK(Material.CARROT_STICK, AuctionLabel.TOOLS, "carrot on a stick|당근 낚싯대"),
	CAULDRON_ITEM(Material.CAULDRON_ITEM, AuctionLabel.BUILDING_SUPPLIES, "cauldron|가마솥"),
	CHAINMAIL_BOOTS(Material.CHAINMAIL_BOOTS, AuctionLabel.TOOLS, "chain boots|사슬 부츠"),
	CHAINMAIL_CHESTPLATE(Material.CHAINMAIL_CHESTPLATE, AuctionLabel.TOOLS, "chain chestplate|사슬 갑옷"),
	CHAINMAIL_HELMET(Material.CHAINMAIL_HELMET, AuctionLabel.TOOLS, "chain helmet|사슬 투구"),
	CHAINMAIL_LEGGINGS(Material.CHAINMAIL_LEGGINGS, AuctionLabel.TOOLS, "chain leggings|사슬 레깅스"),
	CHEST(Material.CHEST, AuctionLabel.BUILDING_SUPPLIES, "chest|상자"),
	CLAY(Material.CLAY, AuctionLabel.BUILDING_SUPPLIES, "clay|점토"),
	CLAY_BALL(Material.CLAY_BALL, AuctionLabel.OTHERS, "clay|점토"),
	CLAY_BRICK(Material.CLAY_BRICK, AuctionLabel.OTHERS, "brick|벽돌"),
	COAL(Material.COAL, AuctionLabel.MINERALS, "coal|석탄"),
	CHARCOAL(Material.COAL, (short) 1, AuctionLabel.MINERALS, "charcoal|목탄"),
	COAL_BLOCK(Material.COAL_BLOCK, AuctionLabel.MINERALS, "block of coal|석탄 블록"),
	COAL_ORE(Material.COAL_ORE, AuctionLabel.MINERALS, "coal ore|석탄 광석"),
	COBBLE_WALL(Material.COBBLE_WALL, AuctionLabel.BUILDING_SUPPLIES, "cobblestone wall|조약돌 담장"),
	COBBLESTONE(Material.COBBLESTONE, AuctionLabel.BUILDING_SUPPLIES, "cobblestone|조약돌"),
	COBBLESTONE_STAIRS(Material.COBBLESTONE_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "cobblestone stairs|조약돌 계단"),
	COOKED_BEEF(Material.COOKED_BEEF, AuctionLabel.MEATS, "steak|스테이크|소고기"),
	COOKED_CHICKEN(Material.COOKED_CHICKEN, AuctionLabel.MEATS, "cooked chicken|구운 닭고기|닭고기"),
	COOKED_FISH(Material.COOKED_FISH, AuctionLabel.MEATS, "cooked fish|구운 물고기|물고기"),
	COOKED_MUTTON(Material.COOKED_MUTTON, AuctionLabel.MEATS, "cooked mutton|구운 양고기|양고기"),
	COOKED_RABBIT(Material.COOKED_RABBIT, AuctionLabel.MEATS, "cooked rabbit|구운 토끼고기|토끼고기"),
	COOKIE(Material.COOKIE, AuctionLabel.FARM_PRODUCE, "cookie|쿠키"),
	DARK_OAK_DOOR_ITEM(Material.DARK_OAK_DOOR_ITEM, AuctionLabel.BUILDING_SUPPLIES, "dark oak door|짙은 참나무 문"),
	DARK_OAK_FENCE(Material.DARK_OAK_FENCE, AuctionLabel.BUILDING_SUPPLIES, "dark oak fence|짙은 참나무 울타리"),
	DARK_OAK_FENCE_GATE(Material.DARK_OAK_FENCE_GATE, AuctionLabel.BUILDING_SUPPLIES, "dark oak fence gate|짙은 참나무 울타리 문"),
	DARK_OAK_STAIRS(Material.DARK_OAK_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "dark oak stairs|짙은 참나무 계단"),
	DAYLIGHT_DETECTOR(Material.DAYLIGHT_DETECTOR, AuctionLabel.BUILDING_SUPPLIES, "daylight detector|햇빛 감지기"),
	DEAD_BUSH(Material.DEAD_BUSH, AuctionLabel.BUILDING_SUPPLIES, "dead bush|마른 덤불"),
	DETECTOR_RAIL(Material.DETECTOR_RAIL, AuctionLabel.BUILDING_SUPPLIES, "detector rail|디텍터 레일"),
	DIAMOND(Material.DIAMOND, AuctionLabel.MINERALS, "diamond|다이아몬드"),
	DIAMOND_AXE(Material.DIAMOND_AXE, AuctionLabel.TOOLS, "diamond axe|다이아몬드 도끼"),
	DIAMOND_BARDING(Material.DIAMOND_BARDING, AuctionLabel.OTHERS, "diamond horse armor|다이아몬드 말 갑옷"),
	DIAMOND_BLOCK(Material.DIAMOND_BLOCK, AuctionLabel.MINERALS, "block of diamond|다이아몬드 블록"),
	DIAMOND_BOOTS(Material.DIAMOND_BOOTS, AuctionLabel.TOOLS, "diamond boots|다이아몬드 부츠"),
	DIAMOND_CHESTPLATE(Material.DIAMOND_CHESTPLATE, AuctionLabel.TOOLS, "diamond chestplate|다이아몬드 갑옷"),
	DIAMOND_HELMET(Material.DIAMOND_HELMET, AuctionLabel.TOOLS, "diamond helmet|다이아몬드 투구"),
	DIAMOND_HOE(Material.DIAMOND_HOE, AuctionLabel.TOOLS, "diamond hoe|다이아몬드 괭이"),
	DIAMOND_LEGGINGS(Material.DIAMOND_LEGGINGS, AuctionLabel.TOOLS, "diamond leggings|다이아몬드 괭이"),
	DIAMOND_ORE(Material.DIAMOND_ORE, AuctionLabel.MINERALS, "diamond ore|다이아몬드 광석"),
	DIAMOND_PICKAXE(Material.DIAMOND_PICKAXE, AuctionLabel.TOOLS, "diamond pickaxe|다이아몬드 곡괭이"),
	DIAMOND_SPADE(Material.DIAMOND_SPADE, AuctionLabel.TOOLS, "diamond spade|다이아몬드 삽"),
	DIAMOND_SWORD(Material.DIAMOND_SWORD, AuctionLabel.TOOLS, "diamond sword|다이아몬드 검"),
	DIODE(Material.DIODE, AuctionLabel.BUILDING_SUPPLIES, "redstone repeater|레드스톤 중계기"),
	DIRT(Material.DIRT, AuctionLabel.BUILDING_SUPPLIES, "dirt|흙"),
	DISPENSER(Material.DISPENSER, AuctionLabel.BUILDING_SUPPLIES, "dispenser|발사기"),
	DOUBLE_PLANT(Material.DOUBLE_PLANT, AuctionLabel.BUILDING_SUPPLIES, "sunflower|lilac|double tallgrass|large fern|rose bush|peony|해바라기|라일락|큰 잔디|큰 고사리|장미 덤불|모란|꽃"),
	DROPPER(Material.DROPPER, AuctionLabel.BUILDING_SUPPLIES, "dropper|공급기"),
	EGG(Material.EGG, AuctionLabel.MEATS, "egg|달걀"),
	ENDER_CHEST(Material.ENDER_CHEST, AuctionLabel.BUILDING_SUPPLIES, "ender chest|엔더 상자"),
	ENDER_PEARL(Material.ENDER_PEARL, AuctionLabel.MONSTER_DROPS, "ender pearl|엔더 진주"),
	ENDER_STONE(Material.ENDER_STONE, AuctionLabel.BUILDING_SUPPLIES, "ender stone|엔더 스톤"),
	EXPLOSIVE_MINECART(Material.EXPLOSIVE_MINECART, AuctionLabel.OTHERS, "minecart with tnt|TNT 마인카트"),
	EYE_OF_ENDER(Material.EYE_OF_ENDER, AuctionLabel.OTHERS, "eye of ender|엔더의 눈"),
	FEATHER(Material.FEATHER, AuctionLabel.MEATS, "feather|깃털"),
	FENCE(Material.FENCE, AuctionLabel.BUILDING_SUPPLIES, "oak fence|참나무 울타리"),
	FENCE_GATE(Material.FENCE_GATE, AuctionLabel.BUILDING_SUPPLIES, "oak fence gate|참나무 울타리 문"),
	FERMENTED_SPIDER_EYE(Material.FERMENTED_SPIDER_EYE, AuctionLabel.POTIONS, "fermented spider eye|발효된 거미 눈"),
	FIREBALL(Material.FIREBALL, AuctionLabel.OTHERS, "fireball|화염구"),
	FIREWORK(Material.FIREWORK, AuctionLabel.OTHERS, "firework rocket|폭죽 로켓"),
	FIREWORK_CHARGE(Material.FIREWORK_CHARGE, AuctionLabel.OTHERS, "firework star|불꽃놀이 탄약"),
	FISHING_ROD(Material.FISHING_ROD, AuctionLabel.TOOLS, "fishing rod|낚싯대"),
	FLINT(Material.FLINT, AuctionLabel.OTHERS, "flint|부싯돌"),
	FLINT_AND_STEEL(Material.FLINT_AND_STEEL, AuctionLabel.TOOLS, "flint and steel|라이터"),
	FLOWER_POT_ITEM(Material.FLOWER_POT_ITEM, AuctionLabel.BUILDING_SUPPLIES, "flower pot|화분"),
	FURNACE(Material.FURNACE, AuctionLabel.BUILDING_SUPPLIES, "furnace|화로"),
	GHAST_TEAR(Material.GHAST_TEAR, AuctionLabel.POTIONS, "ghast tear|가스트의 눈물"),
	GLASS(Material.GLASS, AuctionLabel.BUILDING_SUPPLIES, "glass|유리"),
	GLASS_BOTTLE(Material.GLASS_BOTTLE, AuctionLabel.POTIONS, "glass bottle|유리병"),
	GLOWSTONE(Material.GLOWSTONE, AuctionLabel.BUILDING_SUPPLIES, "growstone|발광석"),
	GLOWSTONE_DUST(Material.GLOWSTONE_DUST, AuctionLabel.OTHERS, "growstone dust|발광석 가루"),
	GOLD_AXE(Material.GOLD_AXE, AuctionLabel.TOOLS, "gold axe|금 도끼"),
	GOLD_BARDING(Material.GOLD_BARDING, AuctionLabel.OTHERS, "gold horse armor|금 말 갑옷"),
	GOLD_BLOCK(Material.GOLD_BLOCK, AuctionLabel.MINERALS, "block of gold|금 블록"),
	GOLD_BOOTS(Material.GOLD_BOOTS, AuctionLabel.TOOLS, "gold boots|금 부츠"),
	GOLD_CHESTPLATE(Material.GOLD_CHESTPLATE, AuctionLabel.TOOLS, "gold chestplate|금 갑옷"),
	GOLD_HELMET(Material.GOLD_HELMET, AuctionLabel.TOOLS, "gold helmet|금 투구"),
	GOLD_HOE(Material.GOLD_HOE, AuctionLabel.TOOLS, "gold hoe|금 괭이"),
	GOLD_INGOT(Material.GOLD_INGOT, AuctionLabel.MINERALS, "gold ingot|금괴"),
	GOLD_LEGGINGS(Material.GOLD_LEGGINGS, AuctionLabel.TOOLS, "gold leggings|금 레깅스"),
	GOLD_NUGGET(Material.GOLD_NUGGET, AuctionLabel.MINERALS, "gold nugget|금 조각"),
	GOLD_ORE(Material.GOLD_ORE, AuctionLabel.MINERALS, "gold ore|금광석"),
	GOLD_PICKAXE(Material.GOLD_PICKAXE, AuctionLabel.TOOLS, "gold pickaxe|금 곡괭이"),
	GOLD_PLATE(Material.GOLD_PLATE, AuctionLabel.BUILDING_SUPPLIES, "weighted pressure plate (light)|무게 갑압판 (경형)"),
	GOLD_RECORD(Material.GOLD_RECORD, AuctionLabel.MONSTER_DROPS, "record|음반"),
	GOLD_SPADE(Material.GOLD_SPADE, AuctionLabel.TOOLS, "gold spade|금 삽"),
	GOLD_SWORD(Material.GOLD_SWORD, AuctionLabel.TOOLS, "gold sword|금 검|금 칼"),
	GOLDEN_APPLE(Material.GOLDEN_APPLE, AuctionLabel.FARM_PRODUCE, "golden apple|황금사과"),
	ENCHANTED_GOLDEN_APPLE(Material.GOLDEN_APPLE, (short) 1, AuctionLabel.FARM_PRODUCE, "enchanted golden apple|마법의 황금사과"),
	GOLDEN_CARROT(Material.GOLDEN_CARROT, AuctionLabel.FARM_PRODUCE, "golden carrot|황금 당근"),
	GRASS(Material.GRASS, AuctionLabel.BUILDING_SUPPLIES, "grass|잔디"),
	GRAVEL(Material.GRAVEL, AuctionLabel.BUILDING_SUPPLIES, "grass|자갈"),
	GREEN_RECORD(Material.GREEN_RECORD, AuctionLabel.MONSTER_DROPS, "record|음반"),
	GRILLED_PORK(Material.GRILLED_PORK, AuctionLabel.MEATS, "cooked porkchop|구운 돼지고기|돼지고기"),
	HARD_CLAY(Material.HARD_CLAY, AuctionLabel.BUILDING_SUPPLIES, "hardened clay|굳은 점토"),
	HAY_BLOCK(Material.HAY_BLOCK, AuctionLabel.FARM_PRODUCE, "hay bale|건초 더미"),
	HOPPER(Material.HOPPER, AuctionLabel.BUILDING_SUPPLIES, "hopper|깔때기"),
	HOPPER_MINECART(Material.HOPPER_MINECART, AuctionLabel.OTHERS, "minecart with hopper|깔때기 마인카트"),
	ICE(Material.ICE, AuctionLabel.BUILDING_SUPPLIES, "ice|얼음"),
	INK_SACK(Material.INK_SACK, (short) 0, AuctionLabel.OTHERS, "ink sac|먹물"),
	DYE_1(Material.INK_SACK, (short) 1, AuctionLabel.OTHERS, "dye|염료"),
	DYE_2(Material.INK_SACK, (short) 2, AuctionLabel.OTHERS, "dye|염료"),
	DYE_3(Material.INK_SACK, (short) 3, AuctionLabel.OTHERS, "dye|염료"),
	LAPIS_LAZULI(Material.INK_SACK, (short) 4, AuctionLabel.MINERALS, "lapis lazuli|청금석"),
	DYE_5(Material.INK_SACK, (short) 5, AuctionLabel.OTHERS, "dye|염료"),
	DYE_6(Material.INK_SACK, (short) 6, AuctionLabel.OTHERS, "dye|염료"),
	DYE_7(Material.INK_SACK, (short) 7, AuctionLabel.OTHERS, "dye|염료"),
	DYE_8(Material.INK_SACK, (short) 8, AuctionLabel.OTHERS, "dye|염료"),
	DYE_9(Material.INK_SACK, (short) 9, AuctionLabel.OTHERS, "dye|염료"),
	DYE_10(Material.INK_SACK, (short) 10, AuctionLabel.OTHERS, "dye|염료"),
	DYE_11(Material.INK_SACK, (short) 11, AuctionLabel.OTHERS, "dye|염료"),
	DYE_12(Material.INK_SACK, (short) 12, AuctionLabel.OTHERS, "dye|염료"),
	DYE_13(Material.INK_SACK, (short) 13, AuctionLabel.OTHERS, "dye|염료"),
	DYE_14(Material.INK_SACK, (short) 14, AuctionLabel.OTHERS, "dye|염료"),
	BONE_MEAL(Material.INK_SACK, (short) 15, AuctionLabel.MONSTER_DROPS, "bone meal|뼛가루"),
	IRON_AXE(Material.IRON_AXE, AuctionLabel.TOOLS, "iron axe|철 도끼"),
	IRON_BARDING(Material.IRON_BARDING, AuctionLabel.OTHERS, "iron horse armor|철 말 갑옷"),
	IRON_BLOCK(Material.IRON_BLOCK, AuctionLabel.MINERALS, "block of iron|철 블록"),
	IRON_BOOTS(Material.IRON_BOOTS, AuctionLabel.TOOLS, "iron boots|철 부츠"),
	IRON_CHESTPLATE(Material.IRON_CHESTPLATE, AuctionLabel.TOOLS, "iron chestplate|철 갑옷"),
	IRON_DOOR(Material.IRON_DOOR, AuctionLabel.BUILDING_SUPPLIES, "iron door|철문"),
	IRON_FENCE(Material.IRON_FENCE, AuctionLabel.BUILDING_SUPPLIES, "iron bars|철창"),
	IRON_HELMET(Material.IRON_HELMET, AuctionLabel.TOOLS, "iron helmet|철 투구"),
	IRON_HOE(Material.IRON_HOE, AuctionLabel.TOOLS, "iron hoe|철 괭이"),
	IRON_INGOT(Material.IRON_INGOT, AuctionLabel.MINERALS, "iron ingot|철괴"),
	IRON_LEGGINGS(Material.IRON_LEGGINGS, AuctionLabel.TOOLS, "iron leggings|철 레깅스"),
	IRON_ORE(Material.IRON_ORE, AuctionLabel.MINERALS, "iron ore|철광석"),
	IRON_PICKAXE(Material.IRON_PICKAXE, AuctionLabel.TOOLS, "iron pickaxe|철 곡괭이"),
	IRON_PLATE(Material.IRON_PLATE, AuctionLabel.BUILDING_SUPPLIES, "weighted pressure plate (heavy)|무게 갑압판 (중형)"),
	IRON_SPADE(Material.IRON_SPADE, AuctionLabel.TOOLS, "iron spade|철 삽"),
	IRON_SWORD(Material.IRON_SWORD, AuctionLabel.TOOLS, "iron sword|철 검|철 칼"),
	IRON_TRAPDOOR(Material.IRON_TRAPDOOR, AuctionLabel.BUILDING_SUPPLIES, "iron trapdoor|철 다락문"),
	ITEM_FRAME(Material.ITEM_FRAME, AuctionLabel.BUILDING_SUPPLIES, "item frame|아이템 액자"),
	JACK_O_LANTERN(Material.JACK_O_LANTERN, AuctionLabel.BUILDING_SUPPLIES, "jack o lantern|잭 오 랜턴"),
	JUKEBOX(Material.JUKEBOX, AuctionLabel.BUILDING_SUPPLIES, "jukebox|주크박스"),
	JUNGLE_DOOR_ITEM(Material.JUNGLE_DOOR_ITEM, AuctionLabel.BUILDING_SUPPLIES, "jungle door|정글 나무 문"),
	JUNGLE_FENCE(Material.JUNGLE_FENCE, AuctionLabel.BUILDING_SUPPLIES, "jungle fence|정글 나무 울타리"),
	JUNGLE_FENCE_GATE(Material.JUNGLE_FENCE_GATE, AuctionLabel.BUILDING_SUPPLIES, "jungle fence gate|정글 나무 울타리 문"),
	JUNGLE_WOOD_STAIRS(Material.JUNGLE_WOOD_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "jungle wood stairs|정글 나무 계단"),
	LADDER(Material.LADDER, AuctionLabel.BUILDING_SUPPLIES, "ladder|사다리"),
	LAPIS_BLOCK(Material.LAPIS_BLOCK, AuctionLabel.MINERALS, "lapis lazuli block|청금석 블록"),
	LAPIS_ORE(Material.LAPIS_ORE, AuctionLabel.MINERALS, "lapis ore|청금석 광석"),
	LAVA_BUCKET(Material.LAVA_BUCKET, AuctionLabel.MINERALS, "lava bucket|용암 양동이"),
	LEASH(Material.LEASH, AuctionLabel.OTHERS, "lead|끈"),
	LEATHER(Material.LEATHER, AuctionLabel.MEATS, "leather|가죽"),
	LEATHER_BOOTS(Material.LEATHER_BOOTS, AuctionLabel.TOOLS, "leather boots|가죽 부츠"),
	LEATHER_CHESTPLATE(Material.LEATHER_CHESTPLATE, AuctionLabel.TOOLS, "leather chestplate|가죽 갑옷"),
	LEATHER_HELMET(Material.LEATHER_HELMET, AuctionLabel.TOOLS, "leather helmet|가죽 투구"),
	LEATHER_LEGGINGS(Material.LEATHER_LEGGINGS, AuctionLabel.TOOLS, "leather leggings|가죽 레깅스"),
	LEAVES_OAK(Material.LEAVES, (short) 0, AuctionLabel.BUILDING_SUPPLIES, "oak leaves|참나무 잎"),
	LEAVES_SPRUCE(Material.LEAVES, (short) 1, AuctionLabel.BUILDING_SUPPLIES, "spruce leaves|가문비나무 잎"),
	LEAVES_BIRCH(Material.LEAVES, (short) 2, AuctionLabel.BUILDING_SUPPLIES, "birch leaves|자작나무 잎"),
	LEAVES_JUNGLE(Material.LEAVES, (short) 3, AuctionLabel.BUILDING_SUPPLIES, "jungle leaves|정글 나무 잎"),
	LEAVES_ACACIA(Material.LEAVES_2, (short) 0, AuctionLabel.BUILDING_SUPPLIES, "acacia leaves|아카시아 잎"),
	LEAVES_DARK_OAK(Material.LEAVES_2, (short) 1, AuctionLabel.BUILDING_SUPPLIES, "dark oak leaves|짙은 참나무 잎"),
	LEVER(Material.LEVER, AuctionLabel.BUILDING_SUPPLIES, "lever|레버"),
	LOG_OAK(Material.LOG, (short) 0, AuctionLabel.BUILDING_SUPPLIES, "oak log|참나무"),
	LOG_SPRUCE(Material.LOG, (short) 1, AuctionLabel.BUILDING_SUPPLIES, "spruce log|가문비나무"),
	LOG_BIRCH(Material.LOG, (short) 2, AuctionLabel.BUILDING_SUPPLIES, "birch log|자작나무"),
	LOG_JUNGLE(Material.LOG, (short) 3, AuctionLabel.BUILDING_SUPPLIES, "jungle log|정글 나무"),
	LOG_ACACIA(Material.LOG_2, (short) 0, AuctionLabel.BUILDING_SUPPLIES, "acacia log|아카시아 나무"),
	LOG_DARK_OAK(Material.LOG_2, (short) 1, AuctionLabel.BUILDING_SUPPLIES, "dark oak log|짙은 참나무"),
	LONG_GRASS(Material.LONG_GRASS, AuctionLabel.BUILDING_SUPPLIES, "long grass|잔디"),
	MAGMA_CREAM(Material.MAGMA_CREAM, AuctionLabel.POTIONS, "magma cream|마그마 크림"),
	MELON(Material.MELON, AuctionLabel.FARM_PRODUCE, "melon|수박"),
	MELON_BLOCK(Material.MELON_BLOCK, AuctionLabel.FARM_PRODUCE, "melon|수박"),
	MELON_SEEDS(Material.MELON_SEEDS, AuctionLabel.FARM_PRODUCE, "melon seeds|수박씨"),
	MILK_BUCKET(Material.MILK_BUCKET, AuctionLabel.MEATS, "milk bucket|우유 양동이"),
	MINECART(Material.MINECART, AuctionLabel.OTHERS, "minecart|마인카트"),
	MONSTER_EGG(Material.MONSTER_EGG, AuctionLabel.FARM_PRODUCE, "spawn egg|스폰 알|스폰알"),
	MOSSY_COBBLESTONE(Material.MOSSY_COBBLESTONE, AuctionLabel.BUILDING_SUPPLIES, "mossy cobblestone|이끼 낀 돌|이끼 조약돌"),
	MUSHROOM_SOUP(Material.MUSHROOM_SOUP, AuctionLabel.FARM_PRODUCE, "mushroom soup|버섯 스튜"),
	MUTTON(Material.MUTTON, AuctionLabel.MEATS, "mutton|익히지 않은 양고기|양고기"),
	MYCEL(Material.MYCEL, AuctionLabel.BUILDING_SUPPLIES, "mycelium|균사체"),
	NETHER_BRICK(Material.NETHER_BRICK, AuctionLabel.BUILDING_SUPPLIES, "nether brick|지옥 벽돌"),
	NETHER_BRICK_ITEM(Material.NETHER_BRICK_ITEM, AuctionLabel.BUILDING_SUPPLIES, "nether brick|지옥 벽돌"),
	NETHER_BRICK_STAIRS(Material.NETHER_BRICK_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "nether brick stairs|지옥 벽돌 계단"),
	NETHER_FENCE(Material.NETHER_FENCE, AuctionLabel.BUILDING_SUPPLIES, "nether brick fence|지옥 벽돌 울타리"),
	NETHER_STALK(Material.NETHER_STALK, AuctionLabel.POTIONS, "nether wart|지옥 사마귀"),
	NETHERRACK(Material.NETHERRACK, AuctionLabel.BUILDING_SUPPLIES, "netherrack|네더랙"),
	NOTE_BLOCK(Material.NOTE_BLOCK, AuctionLabel.BUILDING_SUPPLIES, "note block|노트 블록"),
	OBSIDIAN(Material.OBSIDIAN, AuctionLabel.BUILDING_SUPPLIES, "obsidian|흑요석"),
	PACKED_ICE(Material.PACKED_ICE, AuctionLabel.BUILDING_SUPPLIES, "packed ice|단단한 얼음"),
	PAINTING(Material.PAINTING, AuctionLabel.BUILDING_SUPPLIES, "painting|그림"),
	PAPER(Material.PAPER, AuctionLabel.OTHERS, "paper|종이"),
	PISTON_BASE(Material.PISTON_BASE, AuctionLabel.BUILDING_SUPPLIES, "piston|피스톤"),
	PISTON_STICKY_BASE(Material.PISTON_STICKY_BASE, AuctionLabel.BUILDING_SUPPLIES, "sticky piston|끈끈이 피스톤"),
	POISONOUS_POTATO(Material.POISONOUS_POTATO, AuctionLabel.OTHERS, "poisonous potato|독이 있는 감자"),
	PORK(Material.PORK, AuctionLabel.MEATS, "pork|익히지 않은 돼지고기|돼지고기"),
	POTATO_ITEM(Material.POTATO_ITEM, AuctionLabel.FARM_PRODUCE, "potato|감자"),
	POTION(Material.POTION, AuctionLabel.POTIONS, "potion|포션"),
	POWERED_MINECART(Material.POWERED_MINECART, AuctionLabel.OTHERS, "minecart with furnace|화로 마인카트"),
	POWERED_RAIL(Material.POWERED_RAIL, AuctionLabel.BUILDING_SUPPLIES, "powered rail|파워 레일"),
	PRISMARINE(Material.PRISMARINE, AuctionLabel.BUILDING_SUPPLIES, "prismarine|프리즈마린"),
	PRISMARINE_CRYSTALS(Material.PRISMARINE_CRYSTALS, AuctionLabel.OTHERS, "prismarine crystals|프리즈마린 수정"),
	PRISMARINE_SHARD(Material.PRISMARINE_SHARD, AuctionLabel.OTHERS, "prismarine shard|프리즈마린 조각"),
	PUMPKIN(Material.PUMPKIN, AuctionLabel.FARM_PRODUCE, "pumpkin|호박"),
	PUMPKIN_PIE(Material.PUMPKIN_PIE, AuctionLabel.FARM_PRODUCE, "pumpkin pie|호박 파이"),
	PUMPKIN_SEEDS(Material.PUMPKIN_SEEDS, AuctionLabel.FARM_PRODUCE, "pumpkin seeds|호박씨"),
	QUARTZ(Material.QUARTZ, AuctionLabel.MINERALS, "nether quartz|네더 석영"),
	QUARTZ_BLOCK(Material.QUARTZ_BLOCK, AuctionLabel.BUILDING_SUPPLIES, "block of quartz|석영 블록"),
	QUARTZ_ORE(Material.QUARTZ_ORE, AuctionLabel.MINERALS, "nether quartz ore|네더 석영 원석"),
	QUARTZ_STAIRS(Material.QUARTZ_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "quartz stairs|석영 계단"),
	RABBIT(Material.RABBIT, AuctionLabel.MEATS, "rabbit|토끼 고기"),
	RABBIT_FOOT(Material.RABBIT_FOOT, AuctionLabel.MEATS, "rabbit foot|토끼발"),
	RABBIT_HIDE(Material.RABBIT_HIDE, AuctionLabel.MEATS, "rabbit hide|토끼 가죽"),
	RABBIT_STEW(Material.RABBIT_STEW, AuctionLabel.MEATS, "rabbit stew|토끼 스튜"),
	RAILS(Material.RAILS, AuctionLabel.BUILDING_SUPPLIES, "rail|레일"),
	RAW_BEEF(Material.RAW_BEEF, AuctionLabel.MEATS, "raw beef|익히지 않은 소고기|소고기"),
	RAW_CHICKEN(Material.RAW_CHICKEN, AuctionLabel.MEATS, "raw chicken|익히지 않은 닭고기|닭고기"),
	RAW_FISH(Material.RAW_FISH, AuctionLabel.MEATS, "raw fish|익히지 않은 물고기|물고기"),
	RECORD_10(Material.RECORD_10, AuctionLabel.MONSTER_DROPS, "record|음반"),
	RECORD_11(Material.RECORD_11, AuctionLabel.MONSTER_DROPS, "record|음반"),
	RECORD_12(Material.RECORD_12, AuctionLabel.MONSTER_DROPS, "record|음반"),
	RECORD_3(Material.RECORD_3, AuctionLabel.MONSTER_DROPS, "record|음반"),
	RECORD_4(Material.RECORD_4, AuctionLabel.MONSTER_DROPS, "record|음반"),
	RECORD_5(Material.RECORD_5, AuctionLabel.MONSTER_DROPS, "record|음반"),
	RECORD_6(Material.RECORD_6, AuctionLabel.MONSTER_DROPS, "record|음반"),
	RECORD_7(Material.RECORD_7, AuctionLabel.MONSTER_DROPS, "record|음반"),
	RECORD_8(Material.RECORD_8, AuctionLabel.MONSTER_DROPS, "record|음반"),
	RECORD_9(Material.RECORD_9, AuctionLabel.MONSTER_DROPS, "record|음반"),
	RED_MUSHROOM(Material.RED_MUSHROOM, AuctionLabel.FARM_PRODUCE, "mushroom|버섯"),
	POPPY(Material.RED_ROSE, (short) 0, AuctionLabel.OTHERS, "poppy|양귀비|꽃"),
	BLUE_ORCHID(Material.RED_ROSE, (short) 1, AuctionLabel.OTHERS, "blue orchid|파란 난초|꽃"),
	ALLIUM(Material.RED_ROSE, (short) 2, AuctionLabel.OTHERS, "allium|파꽃|꽃"),
	AZURE_BLUET(Material.RED_ROSE, (short) 3, AuctionLabel.OTHERS, "azure bluet|푸른 삼백초|꽃"),
	RED_TULIP(Material.RED_ROSE, (short) 4, AuctionLabel.OTHERS, "red tulip|빨간색 튤립|꽃"),
	ORANGE_TULIP(Material.RED_ROSE, (short) 5, AuctionLabel.OTHERS, "orange|주황색 튤립|꽃"),
	WHITE_TULIP(Material.RED_ROSE, (short) 6, AuctionLabel.OTHERS, "white tulip|하얀색 튤립|꽃"),
	PINK_TULIP(Material.RED_ROSE, (short) 7, AuctionLabel.OTHERS, "pink tulip|분홍색 튤립|꽃"),
	OXEYE_DAISY(Material.RED_ROSE, (short) 8, AuctionLabel.OTHERS, "oxeye daisy|데이지|꽃"),
	RED_SANDSTONE(Material.RED_SANDSTONE, AuctionLabel.BUILDING_SUPPLIES, "red sandstone|붉은 사암"),
	RED_SANDSTONE_STAIRS(Material.RED_SANDSTONE_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "red sandstone|붉은 사암 계단"),
	REDSTONE(Material.REDSTONE, AuctionLabel.MINERALS, "redstone|레드스톤"),
	REDSTONE_BLOCK(Material.REDSTONE_BLOCK, AuctionLabel.MINERALS, "block of redstone|레드스톤 블록"),
	REDSTONE_COMPARATOR(Material.REDSTONE_COMPARATOR, AuctionLabel.BUILDING_SUPPLIES, "redstone comparator|레드스톤 비교기"),
	REDSTONE_LAMP_OFF(Material.REDSTONE_LAMP_OFF, AuctionLabel.BUILDING_SUPPLIES, "redstone lamp|레드스톤 조명"),
	REDSTONE_ORE(Material.REDSTONE_ORE, AuctionLabel.MINERALS, "redstone ore|레드스톤 광석"),
	REDSTONE_TORCH_OFF(Material.REDSTONE_TORCH_OFF, AuctionLabel.BUILDING_SUPPLIES, "redstone torch|레드스톤 횃불"),
	ROTTEN_FLESH(Material.ROTTEN_FLESH, AuctionLabel.MONSTER_DROPS, "rotten flesh|썩은 고기"),
	SADDLE(Material.SADDLE, AuctionLabel.OTHERS, "saddle|안장"),
	SAND(Material.SAND, AuctionLabel.BUILDING_SUPPLIES, "sand|모래"),
	SANDSTONE(Material.SANDSTONE, AuctionLabel.BUILDING_SUPPLIES, "sandstone|사암"),
	SANDSTONE_STAIRS(Material.SANDSTONE_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "sandstone stairs|사암 계단"),
	SAPLING_OAK(Material.SAPLING, (short) 0, AuctionLabel.BUILDING_SUPPLIES, "sapling|참나무 묘목"),
	SAPLING_SPRUCE(Material.SAPLING, (short) 1, AuctionLabel.BUILDING_SUPPLIES, "sapling|가문비나무 묘목"),
	SAPLING_BIRCH(Material.SAPLING, (short) 2, AuctionLabel.BUILDING_SUPPLIES, "sapling|자작나무 묘목"),
	SAPLING_JUNGLE(Material.SAPLING, (short) 3, AuctionLabel.BUILDING_SUPPLIES, "sapling|정글 나무 묘목"),
	SAPLING_ACACIA(Material.SAPLING, (short) 4, AuctionLabel.BUILDING_SUPPLIES, "sapling|아카시아 묘목"),
	SAPLING_DARK_OAK(Material.SAPLING, (short) 5, AuctionLabel.BUILDING_SUPPLIES, "sapling|짙은 참나무 묘목"),
	SEA_LANTERN(Material.SEA_LANTERN, AuctionLabel.BUILDING_SUPPLIES, "sea lantern|바다 랜턴"),
	SEEDS(Material.SEEDS, AuctionLabel.FARM_PRODUCE, "seeds|씨앗"),
	SHEARS(Material.SHEARS, AuctionLabel.TOOLS, "shears|가위"),
	SIGN(Material.SIGN, AuctionLabel.BUILDING_SUPPLIES, "sign|표지판"),
	SKULL_ITEM(Material.SKULL_ITEM, AuctionLabel.BUILDING_SUPPLIES, "skull|머리"),
	SLIME_BALL(Material.SLIME_BALL, AuctionLabel.MONSTER_DROPS, "slime ball|슬라임 볼"),
	SLIME_BLOCK(Material.SLIME_BLOCK, AuctionLabel.MONSTER_DROPS, "slime block|슬라임 블럭"),
	SMOOTH_BRICK(Material.SMOOTH_BRICK, AuctionLabel.BUILDING_SUPPLIES, "stone bricks|석재 벽돌"),
	SMOOTH_STAIRS(Material.SMOOTH_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "stone brick stairs|석재 벽돌 계단"),
	SNOW(Material.SNOW, AuctionLabel.BUILDING_SUPPLIES, "snow|눈"),
	SNOW_BALL(Material.SNOW_BALL, AuctionLabel.OTHERS, "snowball|눈덩이"),
	SNOW_BLOCK(Material.SNOW_BLOCK, AuctionLabel.BUILDING_SUPPLIES, "snow|눈"),
	SOUL_SAND(Material.SOUL_SAND, AuctionLabel.BUILDING_SUPPLIES, "soul sand|소울 샌드"),
	SPECKLED_MELON(Material.SPECKLED_MELON, AuctionLabel.POTIONS, "speckled melon|반짝이는 수박"),
	SPIDER_EYE(Material.SPIDER_EYE, AuctionLabel.MONSTER_DROPS, "spider eye|거미 눈"),
	SPONGE(Material.SPONGE, AuctionLabel.BUILDING_SUPPLIES, "sponge|스펀지"),
	SPRUCE_DOOR_ITEM(Material.SPRUCE_DOOR_ITEM, AuctionLabel.BUILDING_SUPPLIES, "spruce door|가문비나무 문"),
	SPRUCE_FENCE(Material.SPRUCE_FENCE, AuctionLabel.BUILDING_SUPPLIES, "spruce fence|가문비나무 울타리"),
	SPRUCE_FENCE_GATE(Material.SPRUCE_FENCE_GATE, AuctionLabel.BUILDING_SUPPLIES, "spruce fence gate|가문비나무 울타리 문"),
	SPRUCE_WOOD_STAIRS(Material.SPRUCE_WOOD_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "spruce wood stairs|가문비나무 계단"),
	STAINED_CLAY(Material.STAINED_CLAY, AuctionLabel.BUILDING_SUPPLIES, "stained clay|염색된 점토"),
	STAINED_GLASS(Material.STAINED_GLASS, AuctionLabel.BUILDING_SUPPLIES, "stained glass|염색된 유리|색유리"),
	STAINED_GLASS_PANE(Material.STAINED_GLASS_PANE, AuctionLabel.BUILDING_SUPPLIES, "stained glass|염색된 유리판|색유리판"),
	STEP(Material.STEP, AuctionLabel.BUILDING_SUPPLIES, "slab|반 블럭"),
	STICK(Material.STICK, AuctionLabel.OTHERS, "stick|막대기"),
	STONE(Material.STONE, AuctionLabel.BUILDING_SUPPLIES, "stone|돌|화강암|부드러운 화강암|섬록암|부드러운 섬록암|안산암|부드러운 안산암"),
	STONE_AXE(Material.STONE_AXE, AuctionLabel.TOOLS, "stone axe|돌 도끼"),
	STONE_BUTTON(Material.STONE_BUTTON, AuctionLabel.OTHERS, "stone button|돌 버튼"),
	STONE_HOE(Material.STONE_HOE, AuctionLabel.TOOLS, "stone hoe|돌 괭이"),
	STONE_PICKAXE(Material.STONE_PICKAXE, AuctionLabel.TOOLS, "stone pickaxe|돌 곡괭이"),
	STONE_PLATE(Material.STONE_PLATE, AuctionLabel.BUILDING_SUPPLIES, "stone pressure plate|돌 갑압판"),
	STONE_SLAB2(Material.STONE_SLAB2, AuctionLabel.BUILDING_SUPPLIES, "slab|반 블록"),
	STONE_SPADE(Material.STONE_SPADE, AuctionLabel.TOOLS, "stone spade|돌 삽"),
	STONE_SWORD(Material.STONE_SWORD, AuctionLabel.TOOLS, "stone sword|돌 검|돌 칼"),
	STORAGE_MINECART(Material.STORAGE_MINECART, AuctionLabel.OTHERS, "minecart with chest|창고 마인카트"),
	STRING(Material.STRING, AuctionLabel.MONSTER_DROPS, "string|실|끈"),
	SUGAR(Material.SUGAR, AuctionLabel.OTHERS, "sugar|설탕"),
	SUGAR_CANE(Material.SUGAR_CANE, AuctionLabel.FARM_PRODUCE, "sugar canes|사탕수수"),
	SULPHUR(Material.SULPHUR, AuctionLabel.MONSTER_DROPS, "sulphur|화약"),
	THIN_GLASS(Material.THIN_GLASS, AuctionLabel.BUILDING_SUPPLIES, "glass pane|유리판"),
	TNT(Material.TNT, AuctionLabel.MINERALS, "tnt"),
	TORCH(Material.TORCH, AuctionLabel.BUILDING_SUPPLIES, "torch"),
	TRAP_DOOR(Material.TRAP_DOOR, AuctionLabel.BUILDING_SUPPLIES, "trap door|다락문"),
	TRAPPED_CHEST(Material.TRAPPED_CHEST, AuctionLabel.BUILDING_SUPPLIES, "trapped chest|덫 상자"),
	TRIPWIRE_HOOK(Material.TRIPWIRE_HOOK, AuctionLabel.BUILDING_SUPPLIES, "trapwire hook|철사덫 갈고리"),
	VINE(Material.VINE, AuctionLabel.BUILDING_SUPPLIES, "vine|덩쿨"),
	WATCH(Material.WATCH, AuctionLabel.TOOLS, "clock|시계"),
	WATER_BUCKET(Material.WATER_BUCKET, AuctionLabel.OTHERS, "water bucket|물 양동이"),
	WATER_LILY(Material.WATER_LILY, AuctionLabel.BUILDING_SUPPLIES, "lily pad|연꽃잎"),
	WEB(Material.WEB, AuctionLabel.BUILDING_SUPPLIES, "web|거미줄"),
	WHEAT(Material.WHEAT, AuctionLabel.FARM_PRODUCE, "wheat|밀"),
	WOOD_OAK(Material.WOOD, (short) 0, AuctionLabel.BUILDING_SUPPLIES, "oak wood planks|참나무 목재"),
	WOOD_SPRUCE(Material.WOOD, (short) 1, AuctionLabel.BUILDING_SUPPLIES, "spruce wood planks|가문비나무 목재"),
	WOOD_BIRCH(Material.WOOD, (short) 2, AuctionLabel.BUILDING_SUPPLIES, "birch wood planks|자작나무 목재"),
	WOOD_JUNGLE(Material.WOOD, (short) 3, AuctionLabel.BUILDING_SUPPLIES, "jungle wood planks|정글 나무 목재"),
	WOOD_ACACIA(Material.WOOD, (short) 4, AuctionLabel.BUILDING_SUPPLIES, "acacia wood planks|아카시아 나무 목재"),
	WOOD_DARK_OAK(Material.WOOD, (short) 5, AuctionLabel.BUILDING_SUPPLIES, "dark oak wood planks|짙은 참나무 목재"),
	WOOD_AXE(Material.WOOD_AXE, AuctionLabel.TOOLS, "wood axe|나무 도끼"),
	WOOD_BUTTON(Material.WOOD_BUTTON, AuctionLabel.TOOLS, "wood button|나무 버튼"),
	WOOD_DOOR(Material.WOOD_DOOR, AuctionLabel.BUILDING_SUPPLIES, "wood door|참나무 문"),
	WOOD_HOE(Material.WOOD_HOE, AuctionLabel.TOOLS, "wood hoe|나무 괭이"),
	WOOD_PICKAXE(Material.WOOD_PICKAXE, AuctionLabel.TOOLS, "wood pickaxe|나무 곡괭이"),
	WOOD_PLATE(Material.WOOD_PLATE, AuctionLabel.BUILDING_SUPPLIES, "wood pressure plate|나무 갑압판"),
	WOOD_SPADE(Material.WOOD_SPADE, AuctionLabel.TOOLS, "wood spade|나무 삽"),
	WOOD_STAIRS(Material.WOOD_STAIRS, AuctionLabel.BUILDING_SUPPLIES, "wood stairs|참나무 계단"),
	WOOD_STEP(Material.WOOD_STEP, AuctionLabel.BUILDING_SUPPLIES, "slab|반 블록"),
	WOOD_SWORD(Material.WOOD_SWORD, AuctionLabel.TOOLS, "wood sword|나무 검|나무 칼"),
	WOOL(Material.WOOL, AuctionLabel.BUILDING_SUPPLIES, "wool|양털|양모"),
	WORKBENCH(Material.WORKBENCH, AuctionLabel.BUILDING_SUPPLIES, "crafting table|조합대"),
	WRITTEN_BOOK(Material.WRITTEN_BOOK, AuctionLabel.OTHERS, "written book|쓰여진 책"),
	YELLOW_FLOWER(Material.YELLOW_FLOWER, AuctionLabel.BUILDING_SUPPLIES, "dandelion|민들레|꽃"),
	
	ANVIL_ABANDONED(ItemStorage.ANVIL_ABANDONED, AuctionLabel.MONSTER_DROPS),
	ANVIL_OLD(ItemStorage.ANVIL_OLD, AuctionLabel.MONSTER_DROPS),
	ANVIL_ENCHANTED(ItemStorage.ANVIL_ENCHANTED, AuctionLabel.MONSTER_DROPS),
	EYE_OF_TELEPORTATION(ItemStorage.EYE_OF_TELEPORTATION, AuctionLabel.MONSTER_DROPS),
	NAME_CHANGER(ItemStorage.NAME_CHANGER, AuctionLabel.MONSTER_DROPS),
	PICK_ME_UP_1(ItemStorage.PICK_ME_UP_1, AuctionLabel.MONSTER_DROPS),
	PICK_ME_UP_2(ItemStorage.PICK_ME_UP_2, AuctionLabel.MONSTER_DROPS),
	ANIMAL_MEDICINE(ItemStorage.ANIMAL_MEDICINE, AuctionLabel.MONSTER_DROPS),
	FURNACE_SPEED_1(ItemStorage.FURNACE_SPEED_1, AuctionLabel.MONSTER_DROPS),
	FURNACE_SPEED_2(ItemStorage.FURNACE_SPEED_2, AuctionLabel.MONSTER_DROPS),
	FURNACE_SPEED_3(ItemStorage.FURNACE_SPEED_3, AuctionLabel.MONSTER_DROPS),
	FURNACE_FUEL_1(ItemStorage.FURNACE_FUEL_1, AuctionLabel.MONSTER_DROPS),
	FURNACE_FUEL_2(ItemStorage.FURNACE_FUEL_2, AuctionLabel.MONSTER_DROPS),
	FURNACE_FUEL_3(ItemStorage.FURNACE_FUEL_3, AuctionLabel.MONSTER_DROPS),
	FURNACE_FORTUNE_1(ItemStorage.FURNACE_FORTUNE_1, AuctionLabel.MONSTER_DROPS),
	FURNACE_FORTUNE_2(ItemStorage.FURNACE_FORTUNE_2, AuctionLabel.MONSTER_DROPS),
	FURNACE_FORTUNE_3(ItemStorage.FURNACE_FORTUNE_3, AuctionLabel.MONSTER_DROPS),
	FURNACE_REMAIN(ItemStorage.FURNACE_REMAIN, AuctionLabel.MONSTER_DROPS),
	DECORATION_HEAD_BOX(ItemStorage.DECORATION_HEAD_BOX, AuctionLabel.MONSTER_DROPS),
	
	OTHERS("Others", AuctionLabel.OTHERS);
	
	private Material type = Material.AIR;
	private short durability = 0;
	private final AuctionLabel label;
	private final List<String> nameList;
	
	private AuctionMaterial(Material type, AuctionLabel label, String name) {
		this.type = type;
		this.label = label;
		this.nameList = Arrays.asList(name.split("\\|"));
	}
	
	private AuctionMaterial(Material type, short durability, AuctionLabel label, String name) {
		this.type = type;
		this.durability = durability;
		this.label = label;
		this.nameList = Arrays.asList(name.split("\\|"));
	}
	
	private AuctionMaterial(ItemStack itemStack, AuctionLabel label) {
		this(ItemStorage.getName(itemStack), label);
	}
	
	private AuctionMaterial(String name, AuctionLabel label) {
		this.label = label;
		this.nameList = Arrays.asList(name.split("\\|"));
	}
	
	public AuctionLabel getLabel() {
		return this.label;
	}
	
	public static AuctionMaterial getAuctionMaterial(ItemStack itemStack) {
		if (itemStack.hasItemMeta() && itemStack.getItemMeta().hasDisplayName()) {
			String displayName = itemStack.getItemMeta().getDisplayName();
			
			for (AuctionMaterial material : values()) {
				if (material.nameList.contains(displayName)) {
					return material;
				}
			}
		}
		
		for (AuctionMaterial material : values()) {
			if (material.type == itemStack.getType()) {
				if (material.type.getMaxDurability() <= 16 && material.durability != itemStack.getDurability())
					continue;
				
				return material;
			}
		}
		
		return AuctionMaterial.OTHERS;
	}
	
	public static List<AuctionMaterial> getAuctionMaterial(String name) {
		List<AuctionMaterial> list = new ArrayList<AuctionMaterial>();
		String mName = name.toLowerCase();
		
		for (AuctionMaterial material : values()) {
			for (String listName : material.nameList) {
				if (listName.contains(mName)) {
					list.add(material);
				}
			}
		}
		
		return list;
	}
}
